countries:
  - DEU
  - FRA
period:
  start: "2015-01-01"
  end: "2016-12-31"
  frequency: "Q"
indicators:
  - id: gdp_real_yoy
    sources:
      - source: WB
        code: NY.GDP.MKTP.KD.ZG
    good_direction: up
    transform: none
scoring:
  standardization: zscore
  smoothing: 0
  weights:
    gdp_real_yoy: 1.0
  min_coverage_ratio: 0.5
excel:
  path: ./output/fixture_macro_ranking.xlsx
  number_format: "#.##0,00"
caching:
  enabled: false
runtime:
  max_workers: 2
allocation:
  min_alloc: 0.0
  max_alloc: 1.0
backtest:
  enabled: true
  no_backfill: false
