[tool.ruff]
line-length = 88
# Keep defaults but ensure stable formatting across devs
exclude = [".venv", "build", "dist", "tests/fixtures"]

[tool.ruff.lint]
extend-ignore = ["E402"]

[tool.black]
line-length = 88
target-version = ['py311']
